# Generated by Django 3.0.6 on 2020-10-04 19:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zagros.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('private_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=zagros.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=zagros.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=750)),
                ('post_content', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=450)),
                ('mim_type', models.CharField(blank=True, max_length=100)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('main-cat', 'Main Category'), ('section', 'Section'), ('card', 'Card'), ('page', 'Page'), ('draft', 'Draft'), ('file', 'File')], db_index=True, default='post', max_length=15)),
                ('author_text', models.CharField(blank=True, max_length=250)),
                ('culture', models.CharField(choices=[('fa-Ir', 'Persian'), ('en', 'English'), ('eo', 'Esperanto')], db_index=True, default='fa-Ir', max_length=10)),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('parent_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_self', to='post.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='post.Post')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='post.Post')),
            ],
        ),
    ]
