# Generated by Django 3.0.6 on 2020-10-21 11:49

from django.db import migrations, models
import draftjs_sanitizer
import zagros.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content_json',
            field=zagros.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=draftjs_sanitizer.clean_draft_js),
        ),
        migrations.AlterField(
            model_name='post',
            name='culture',
            field=models.CharField(choices=[('fa-Ir', 'Persian'), ('en', 'English'), ('all', 'All')], db_index=True, default='fa-Ir', max_length=10),
        ),
    ]
