# Generated by Django 3.0.6 on 2020-10-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201021_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-order_date',), 'permissions': (('manage_posts', 'Manage posts.'),)},
        ),
    ]
