# Generated by Django 3.1.2 on 2020-10-23 02:33

from django.db import migrations, models
import zagros.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201021_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=zagros.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=zagros.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
    ]
