# Generated by Django 3.1.2 on 2020-10-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201023_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcat',
            options={'permissions': (('manage_cats', 'Manage cats.'),)},
        ),
    ]
